name: Frontend CI - TaskSphere

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build frontend Docker image
        run: |
          docker build -t a2-tasksphere-frontend .
